version: 2
jobs:
  build:
    docker:
      - image: circleci/node:14
    steps:
      - checkout
      - add_ssh_keys:
          fingerprints:
            - YOUR_SSH_KEY_FINGERPRINT
      - run: npm install
      - run: npm run build
     # - run: npm test