version: 2
jobs:
  build:
    docker:
      - image: cimg/node:18.18.0
    steps:
      - checkout
      - add_ssh_keys:
          fingerprints:
            - b2:3f:b3:45:66:56:4b:96:19:2c:a8:73:83:67:7a:25
      - run:
          name: Build the project
          command: |
            cd ./back-end
            node -v
            npm -v
            npm install
            npm run build
          environment:
            SECRET_KEY: $SECRET_KEY
      - run:
          name: Create cfg.json file
          command: |
            echo "{\"FLATT_POD_SECRET_KEY\":\"$SECRET_KEY\"}" > ./back-end/cfg.json
            cat ./back-end/cfg.json
