version: 2
jobs:
  build:
    docker:
      - image: circleci/node:14
    steps:
      - checkout
      - run:
        name: Set up SSH key
        command: echo "$SSH_KEY" > /home/circleci/.ssh/id_rsa
      - run: npm install
      - run: npm run build
     # - run: npm test