version: 2
jobs:
  build:
    docker:
      - image: cimg/node:18.18.0
    steps:
      - checkout
      - add_ssh_keys:
          fingerprints:
            - b2:3f:b3:45:66:56:4b:96:19:2c:a8:73:83:67:7a:25
      - run:
          name: Install dependecies
          command: |
            cd ./back-end
            node -v
            npm -v
            npm install
          environment:
            MYSQL_HOST: $FLATTPOD_MYSQL_PROD_HOST
            MYSQL_NONPROD_HOST: $FLATTPOD_MYSQL_NONPROD_HOST
      - run:
          name: Create cfg.json file
          command: |
            echo "{\"FLATTPOD_MYSQL_PROD_HOST\":\"$MYSQL_HOST\"," > ./back-end/cfg.json
            echo "\"FLATTPOD_MYSQL_NONPROD_HOST\":\"$MYSQL_NONPROD_HOST\"}" >> ./back-end/cfg.json
            cat ./back-end/cfg.json
      - run:
          name: Build the project
          command: |
            cd ./back-end
            ls
            npm run build
