version: '3'
services:
  web-server:
    image: test7:latest
    ports:
      - "8080:8080"
  mysql-db:
    image: mysql:8.1.0
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: flattpod
    ports:
      - "3307:3306"
