import KEYS from './env.json';

const initSecrets = ():void => {
  process.env.FLATTPOD_MYSQL_PROD_HOST=KEYS.FLATTPOD_MYSQL_PROD_HOST;
  process.env.FLATTPOD_MYSQL_NONPROD_HOST=KEYS.FLATTPOD_MYSQL_NONPROD_HOST;
  process.env.FLATTPOD_MYSQL_USER=KEYS.FLATTPOD_MYSQL_USER;
  process.env.FLATTPOD_MYSQL_PASSWORD=KEYS.FLATTPOD_MYSQL_PASSWORD;
  process.env.FLATTPOD_MYSQL_DB=KEYS.FLATTPOD_MYSQL_DB;
  process.env.FLATTPOD_MYSQL_LIMIT=KEYS.FLATTPOD_MYSQL_LIMIT;
  process.env.FLATTPOD_MYSQL_PORT=KEYS.FLATTPOD_MYSQL_PORT;
  process.env.FLATTPOD_SERVER_PORT=KEYS.FLATTPOD_SERVER_PORT;
  process.env.FLATTPOD_PROD=KEYS.FLATTPOD_PROD;
};

initSecrets();
